trigger:
  batch: true
  branches:
    include:
      - master
      - develop
      - hotfix/*
      - release/*
      - "*test_deploy*"
pr:
  - master
  - develop


jobs:
  - job: Linux
    timeoutInMinutes: 60
    pool:
      vmImage: "ubuntu-18.04"
    steps:
      - task: InstallSSHKey@0
        inputs:
          knownHostsEntry: $(griddly_known_hosts_entry)
          sshPublicKey: $(griddly_azure_public_key)
          sshPassphrase: $(griddly_azure_passphrase)
          sshKeySecureFile: griddly
      - checkout: self
        submodules: true
        persistCredentials: true
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.7'
          addToPath: true 
        displayName: Set Python 3.7
      - script: |
          set -ex
          wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-bionic.list http://packages.lunarg.com/vulkan/lunarg-vulkan-bionic.list
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt update
          sudo apt install libvulkan1
         
        displayName: Installing Vulkan
      - bash: |
          pip install conan>=1.40.3
        continueOnError: false
        displayName: Install Conan
      - task: CMake@1
        inputs:
          workingDirectory: .
          cmakeArgs: -E make_directory build
        displayName: Create build folder
      - task: CMake@1
        inputs:
          workingDirectory: ./build
          cmakeArgs: .. -DCMAKE_BUILD_TYPE=Release
        displayName: Initialize CMake
      - task: CMake@1
        inputs:
          workingDirectory: ./build
          cmakeArgs: --build .
        displayName: Build
      - bash: |
          GTEST_FILTER=-*BlockObserverTest*:*SpriteObserverTest* GTEST_OUTPUT=xml:test-report.xml ctest --test-dir ./build --verbose
        continueOnError: true
        displayName: Test
      - task: PublishTestResults@2
        inputs:
          failTaskOnFailedTests: true
          testResultsFormat: JUnit # Options: JUnit, NUnit, VSTest, xUnit, cTest
          testResultsFiles: test-report.xml
          testRunTitle: Ubuntu 18.04 Tests
        displayName: Publish C++ Test Results
      - script: |
          set -ex
          cd python 
          pip install -r requirements.txt
          python setup.py install
          pip install pytest pytest-azurepipelines
          python -m pytest
        displayName: Run and Publish Python Tests
  
  - job: PyPiDeployLinux
    dependsOn: Linux
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), contains(variables['Build.SourceBranch'], 'test_deploy')))
    timeoutInMinutes: 60
    pool:
      vmImage: "ubuntu-18.04"
    strategy:
      matrix:
        ManyLinux_p36:
          PythonVersion: 3.6
          PyBin: cp36-cp36m
          PLAT: manylinux2014_x86_64
        ManyLinux_p37:
          PythonVersion: 3.7
          PyBin: cp37-cp37m
          PLAT: manylinux2014_x86_64
        ManyLinux_p38:
          PythonVersion: 3.8
          PyBin: cp38-cp38
          PLAT: manylinux2014_x86_64
    steps:
      - task: InstallSSHKey@0
        inputs:
          knownHostsEntry: $(griddly_known_hosts_entry)
          sshPublicKey: $(griddly_azure_public_key)
          sshPassphrase: $(griddly_azure_passphrase)
          sshKeySecureFile: griddly
      - checkout: self
        submodules: true
        persistCredentials: true
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(PythonVersion)
          addToPath: true 
        displayName: Set Python $(PythonVersion)
      - bash: |
          pip install conan>=1.40.3
        continueOnError: false
        displayName: Install Conan
      - script: |
          set -ex
          export GRIDDLY_ROOT=$(pwd)
          export PYBIN=$(PyBin)
          export PYVERSION=$(PythonVersion)
          
          ./python/manylinux/manylinux-build.sh
        displayName: Build Wheels
      - task: TwineAuthenticate@1
        displayName: "Twine Authenticate (test)"
        inputs:
          pythonUploadServiceConnection: pypitest
        condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'test_deploy'))
      - task: TwineAuthenticate@1
        displayName: "Twine Authenticate (live)"
        inputs:
          pythonUploadServiceConnection: pypilive
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      - script: |
          pip install twine
          cd python
          python -m twine upload -r "griddly" --config-file $(PYPIRC_PATH) dist/*.whl
        displayName: Deploy To PyPi

  - job: Windows
    variables:
      VULKAN_SDK: C:/VulkanSDK/1.2.148.0
    timeoutInMinutes: 60
    pool:
      vmImage: "windows-latest"
    steps:
      - task: InstallSSHKey@0
        inputs:
          knownHostsEntry: $(griddly_known_hosts_entry)
          sshPublicKey: $(griddly_azure_public_key)
          sshPassphrase: $(griddly_azure_passphrase)
          sshKeySecureFile: griddly
      - checkout: self
        submodules: true
        persistCredentials: true
      - task: UsePythonVersion@0
        inputs:
          versionSpec: 3.7
          addToPath: true 
        displayName: Set Python 3.7
      - bash: |
          pip install conan>=1.40.3
        continueOnError: false
        displayName: Install Conan
      - bash: |
          set -ex
          curl -L -o "vulkan-installer.exe" "https://griddyvulkan.s3.amazonaws.com/VulkanSDK-1.2.148.0-Installer.exe"
          # This makes sure we wait for the vulkan SDK to complete installation
          _=$(echo "vulkan-installer.exe /S" | cmd)
          curl -L -o "vulkan-runtime.zip" "https://griddyvulkan.s3.amazonaws.com/vulkan-1.2.148.0-runtime-components.zip"
          unzip vulkan-runtime.zip
          cp VulkanRT-1.2.148.0-Components/x64/vulkaninfo.exe $VULKAN_SDK/Bin
          cp VulkanRT-1.2.148.0-Components/x64/vulkan-1.dll $VULKAN_SDK/Bin
        displayName: Installing Vulkan
      - task: CMake@1
        inputs:
          workingDirectory: .
          cmakeArgs: -E make_directory build
        displayName: Create build folder
      - task: CMake@1
        inputs:
          workingDirectory: ./build
          cmakeArgs: .. -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE="$(which python)" -DPYBIND11_PYTHON_VERSION=3.7
        displayName: Initialize CMake
      - task: CMake@1
        inputs:
          workingDirectory: ./build
          cmakeArgs: --build . --config Release
        displayName: Build
      - bash: |
          GTEST_FILTER=-*BlockObserverTest*:*SpriteObserverTest* GTEST_OUTPUT=xml:test-report.xml ctest --test-dir ./build --verbose -C Release
        continueOnError: true
        displayName: Test
      - task: PublishTestResults@2
        inputs:
          failTaskOnFailedTests: true
          testResultsFormat: JUnit # Options: JUnit, NUnit, VSTest, xUnit, cTest
          testResultsFiles: test-report.xml
          testRunTitle: Windows Tests
        displayName: Publish C++ Test Results
      - bash: |
          set -ex
          export PATH=$PATH:/c/VulkanSDK/1.2.148.0/Bin
          echo $PATH
          cd python
          pip install -r requirements.txt
          python setup.py install
          pip install pytest pytest-azurepipelines
          python -m pytest
        displayName: Run and Publish Python Tests

  - job: PyPiDeployWindows
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), contains(variables['Build.SourceBranch'], 'test_deploy')))
    dependsOn: Windows
    variables:
      VULKAN_SDK: C:/VulkanSDK/1.2.148.0
    timeoutInMinutes: 60
    pool:
      vmImage: "windows-latest"
    strategy:
      matrix:
        Windows_p36:
          PythonVersion: 3.6
        Windows_p37:
          PythonVersion: 3.7
        Windows_p38:
          PythonVersion: 3.8
    steps:
      - task: InstallSSHKey@0
        inputs:
          knownHostsEntry: $(griddly_known_hosts_entry)
          sshPublicKey: $(griddly_azure_public_key)
          sshPassphrase: $(griddly_azure_passphrase)
          sshKeySecureFile: griddly
      - checkout: self
        submodules: true
        persistCredentials: true
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(PythonVersion)
          addToPath: true 
        displayName: Set Python $(PythonVersion)
      - bash: |
          pip install conan>=1.40.3
        continueOnError: false
        displayName: Install Conan
      - bash: |
          set -ex
          curl -L -o "vulkan-installer.exe" "https://griddyvulkan.s3.amazonaws.com/VulkanSDK-1.2.148.0-Installer.exe"
          # This makes sure we wait for the vulkan SDK to complete installation
          _=$(echo "vulkan-installer.exe /S" | cmd)
          curl -L -o "vulkan-runtime.zip" "https://griddyvulkan.s3.amazonaws.com/vulkan-1.2.148.0-runtime-components.zip"
          unzip vulkan-runtime.zip
          cp VulkanRT-1.2.148.0-Components/x64/vulkaninfo.exe $VULKAN_SDK/Bin
          cp VulkanRT-1.2.148.0-Components/x64/vulkan-1.dll $VULKAN_SDK/Bin
        displayName: Installing Vulkan
      - bash: |
          set -ex
          cmake -E make_directory build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --target python_griddly --config Release
        displayName: Build
      - script: |
          cd python
          pip install wheel setuptools
          python setup.py bdist_wheel
        displayName: Build Wheels
      - task: TwineAuthenticate@1
        displayName: "Twine Authenticate (test)"
        inputs:
          pythonUploadServiceConnection: pypitest
        condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'test_deploy'))
      - task: TwineAuthenticate@1
        displayName: "Twine Authenticate (live)"
        inputs:
          pythonUploadServiceConnection: pypilive
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      - script: |
          pip install twine
          cd python
          python -m twine upload -r "griddly" --config-file $(PYPIRC_PATH) dist/*.whl
        displayName: Deploy To PyPi

  - job: MacOS
    timeoutInMinutes: 60
    pool:
      vmImage: "macOS-latest"
    steps:
      - task: InstallSSHKey@0
        inputs:
          knownHostsEntry: $(griddly_known_hosts_entry)
          sshPublicKey: $(griddly_azure_public_key)
          sshPassphrase: $(griddly_azure_passphrase)
          sshKeySecureFile: griddly
      - checkout: self
        submodules: true
        persistCredentials: true
      - task: UsePythonVersion@0
        inputs:
          versionSpec: 3.7
          addToPath: true 
        displayName: Set Python 3.7
        name: py
      - bash: |
          pip install conan>=1.40.3
        continueOnError: false
        displayName: Install Conan
      - bash: |
          set -ex
          curl -L -o "vulkansdk-macos-1.2.148.0.dmg" "https://griddyvulkan.s3.amazonaws.com/vulkansdk-macos-1.2.148.0.dmg"
          hdiutil attach vulkansdk-macos-1.2.148.0.dmg
          cd /Volumes/vulkansdk-macos-1.2.148.0
          ./install_vulkan.py --force-install
        displayName: Installing Vulkan
      - task: CMake@1
        inputs:
          workingDirectory: .
          cmakeArgs: -E make_directory build
        displayName: Create build folder
      - task: CMake@1
        inputs:
          workingDirectory: ./build
          cmakeArgs: .. -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE="$(which python)" -DPYBIND11_PYTHON_VERSION=3.7
        displayName: Initialize CMake
      - task: CMake@1
        inputs:
          workingDirectory: ./build
          cmakeArgs: --build . --config Release
        displayName: Build
      - bash: |
          GTEST_FILTER=-*BlockObserverTest*:*SpriteObserverTest* GTEST_OUTPUT=xml:test-report.xml ctest --test-dir ./build --verbose -C Release
        continueOnError: true
        displayName: Test
      - task: PublishTestResults@2
        inputs:
          failTaskOnFailedTests: true
          testResultsFormat: JUnit # Options: JUnit, NUnit, VSTest, xUnit, cTest
          testResultsFiles: test-report.xml
          testRunTitle: MacOS Tests
        displayName: Publish C++ Test Results
      - script: |
          set -ex
          cd python 
          pip install -r requirements.txt
          python setup.py install
          pip install pytest pytest-azurepipelines
          python -m pytest
        displayName: Run and Publish Python Tests

  - job: PyPiDeployMacOS
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), contains(variables['Build.SourceBranch'], 'test_deploy')))
    dependsOn: MacOS
    timeoutInMinutes: 60
    pool:
      vmImage: "macOS-latest"
    strategy:
      matrix:
        MacOS_p36:
          PythonVersion: 3.6
        MacOS_p37:
          PythonVersion: 3.7
        MacOS_p38:
          PythonVersion: 3.8
    steps:
      - task: InstallSSHKey@0
        inputs:
          knownHostsEntry: $(griddly_known_hosts_entry)
          sshPublicKey: $(griddly_azure_public_key)
          sshPassphrase: $(griddly_azure_passphrase)
          sshKeySecureFile: griddly
      - checkout: self
        submodules: true
        persistCredentials: true
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(PythonVersion)
          addToPath: true 
        displayName: Set Python $(PythonVersion)
        name: py
      - bash: |
          pip install conan>=1.40.3
        continueOnError: false
        displayName: Install Conan
      - bash: |
          set -ex
          curl -L -o "vulkansdk-macos-1.2.148.0.dmg" "https://griddyvulkan.s3.amazonaws.com/vulkansdk-macos-1.2.148.0.dmg"
          hdiutil attach vulkansdk-macos-1.2.148.0.dmg
          cd /Volumes/vulkansdk-macos-1.2.148.0
          ./install_vulkan.py --force-install
        displayName: Installing Vulkan
      - task: CMake@1
        inputs:
          workingDirectory: .
          cmakeArgs: -E make_directory build
        displayName: Create build folder
      - task: CMake@1
        inputs:
          workingDirectory: ./build
          cmakeArgs: .. -DCMAKE_BUILD_TYPE=Release
        displayName: Initialize CMake
      - task: CMake@1
        inputs:
          workingDirectory: ./build
          cmakeArgs: --build . --target python_griddly --config Release
        displayName: Build
      - script: |
          cd python
          pip install wheel setuptools
          python setup.py bdist_wheel
        displayName: Build Wheels
      - task: TwineAuthenticate@1
        displayName: "Twine Authenticate (test)"
        inputs:
          pythonUploadServiceConnection: pypitest
        condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'test_deploy'))
      - task: TwineAuthenticate@1
        displayName: "Twine Authenticate (live)"
        inputs:
          pythonUploadServiceConnection: pypilive
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      - script: |
          pip install twine
          cd python
          python -m twine upload -r "griddly" --config-file $(PYPIRC_PATH) dist/*.whl
        displayName: Deploy To PyPi
  
